### ISSUE TITLE
Static ratings

### ISSUE THREAD

**Issue by stevelacey** [LunarLogic/starability#13]
A typical use-case (or at least my use-case) is not only to collect these ratings but also render them back to the user. I currently do this with font-awesome icons because they look like your stars, they're scalable, I am lazy, and you've used a sprite for the images – an (accessible) example/support for this would be handy for others I am sure.

**Comment by szynszyliszys** [comment]
Can you show how you would like to show user's ratings @stevelacey?

**Comment by stevelacey** [comment]
![screen shot 2016-12-07 at 15 59 07](https://cloud.githubusercontent.com/assets/289531/20959478/2e1108a0-bc96-11e6-8079-6e96c1db1bce.png)

**Comment by deleugpn** [comment]
I'm currently facing a similar issue here. I think my goal would be just disabling hover effect so the presentation can have a more static appearance.

**Comment by szynszyliszys** [comment]
@stevelacey @deleugpn I added the basic functionality to show the ratings as integers. To show the float number results you could use similar markup, but use `span` instead of :after pseudoelement and define it's width with Javascript. Example: you need to show the 3.23 rating. You store it as data-rating="3.23" and grab the span element inside the `starability-result`. Now you need to add the width of 3.23*star-width to this span with JS.
