### ISSUE TITLE
Accessibility: keyboard arrows work in reverse order

### ISSUE THREAD

**Issue by dandv** [LunarLogic/starability#15]
As I [mentioned on Lea's blog](http://lea.verou.me/2011/08/accessible-star-rating-widget-with-pure-css/#comment-3122395653), when pressing the left/right arrows with the star rating control focused, the focus moves in the opposite direction: pressing the right arrow moves the focus to the left, and the other way around.

**Comment by szynszyliszys** [comment]
Hi @dandv I know this is an issue. There were trials to change it (both mine and contributors'), but the cost of fixing it was always greater than the gain here:  #https://github.com/LunarLogic/starability/pull/12.

If you have a good idea how that could be fixed without breaking the rest of the functionality (tabbing was the issue usually), then I can consider looking into that.

Without a precise solution proposal I am reluctant to pick up yet another fight with this because:
1. People with vision impairment, who are using screen readers, hear that they are decreasing the rating (the rates go in descending order in markup) so it is still quite clear what is going on. Might be just a bit confusing at first, but is bearable. They also are unable to see the weird behaviour.
2. People who use arrows for conveniance can quickly figure out what is going on and make the changes based on what they see.
3. Up/down arrows work as expected.

**Comment by dandv** [comment]
Hi Anna, how about [this](http://codepen.io/mburnette/pen/eNNZbm) approach?

**Comment by szynszyliszys** [comment]
I think that feedback on hover is a thing that I would rather keep in the library. Maybe there is a better solution that I am not aware of at the moment. I will keep looking, thank you for taking an interest in this repository. :)

**Comment by dandv** [comment]
Here's a [method](http://jsfiddle.net/y9zeLr1n/26/) that doesn't reverse the order of the inputs, and supports hover. Could it be made accessible?

**Comment by dandv** [comment]
Overall thoughts: since accessibility is the main differentiator of this widget (it's in the title after all), it might be worth adding some JavaScript for fixing the left/right issue. From [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/An_overview_of_accessible_web_applications_and_widgets):

>  JavaScript has traditionally had a reputation for being inaccessible to users of assistive technologies such as screen readers, but there are now ways to create dynamic web user interfaces that are accessible to a wide variety of users.

**Comment by dandv** [comment]
Ha - someone did it! [Unicode characters, no JS, keyboard accessible the "right" way](http://dabblet.com/gist/1722368).

**Comment by szynszyliszys** [comment]
@dandv in Firefox it still goes backwards. As of Javascript, I tend to prefer CSS only solutions. It makes it easier to pick them up and use for people who are fairly new to front-end development... But on the other hand, parsing the rating result usually requires JS anyway. I will try to look into that.

**Comment by dandv** [comment]
I've just updated the [CSS-only star rating to use labels](http://jsbin.com/zejeba/edit?html,css,output) - thoughts?

**Comment by szynszyliszys** [comment]
@dandv in Firefox it works exactly as my solution, arrows go the other way around. I wonder why it works in Chrome then... Will check that later when I have a moment. Thanks for testing this.

**Comment by szynszyliszys** [comment]
@dandv I think I solved it. I can't believe this can be so simple and no one thought of this before. Please give me a sanity check on this one: https://jsbin.com/yikeyit/edit?html,css,output

**Comment by szynszyliszys** [comment]
This is fixed in a version 2.0.0.
